#!/bin/csh -f
################################################################################
# simulation top mcript
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim mcript dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
     
vlog +define+SC_R3_K3_2D\
     +define+COL=9\
     +define+ROW=3\
     -f ../filelist/filelist_sc_r3_k3_2d.f  

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim -voptargs=+acc=npr work.tb_sc -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -hexadecimal tb_sc/clock          
add wave -noupdate -format logic -hexadecimal tb_sc/reset    
add wave -noupdate -format logic -hexadecimal tb_sc/in_ready      
add wave -noupdate -format logic -hexadecimal tb_sc/in_matrix         
add wave -noupdate -format logic -hexadecimal tb_sc/in_weight      
add wave -noupdate -format logic -hexadecimal tb_sc/out_data        
add wave -noupdate -format logic -hexadecimal tb_sc/out_valid    
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/scs_0/*
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/scs_1/*
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/scs_2/*
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain0_fifo3/io_in
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain0_fifo0/io_in
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain0_fifo9/io_in
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain1_fifo1/io_in
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain1_fifo8/io_in
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain2_fifo2/io_in
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain2_fifo1/io_in
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain2_fifo7/io_in

add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain0_fifo3/io_out
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain0_fifo0/io_out
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain0_fifo9/io_out
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain1_fifo1/io_out
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain1_fifo8/io_out
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain2_fifo2/io_out
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain2_fifo1/io_out
add wave -noupdate -format logic -hexadecimal tb_sc/u_sc_r3_k3_2d/chain2_fifo7/io_out




     
run 10 us                                                                            

