#!/bin/csh -f
################################################################################
# simulation top mcript
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim mcript dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
     
vlog +define+SC_R3_K3_2D\
     +define+COL=9\
     +define+ROW=5\
     -f ../filelist/filelist_sc_r3_k3_2d.f  

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim -voptargs=+acc=npr work.tb_sc -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -unsigned tb_sc/clock          
add wave -noupdate -format logic -unsigned tb_sc/reset    
add wave -noupdate -format logic -unsigned tb_sc/din_ready      
add wave -noupdate -format logic -unsigned tb_sc/din            
add wave -noupdate -format logic -unsigned tb_sc/dout_vld       
add wave -noupdate -format logic -unsigned tb_sc/din_wt         
add wave -noupdate -format logic -unsigned tb_sc/dout           
run 10 us                                                                            

